"""added order status table

Revision ID: 20a9269dbc9c
Revises: 
Create Date: 2025-02-13 18:34:01.867007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a9269dbc9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###
